### ISSUE TITLE
Javascript JSDOC comments not removed

### ISSUE THREAD

**Issue by ted-dev-42** [rioj7/remove-comments#1]
try to remove comments from this one: http://chaijs.com/chai.js, it doesn't work.

**Comment by rioj7** [comment]
@ted-dev-42 These 'comments' are treated by the extension as JSDOC strings, I use them in my JS code to keep/help TypeScript happy. For me they are one-lineners.

I will add a command to mark these as comments. It will be a one shot mark, only for the next invocation of the **Remove comment** command.

**Comment by rioj7** [comment]
@ted-dev-42 Try v1.5.0, run `Comments: Mark JSDOC String as comment.` before `Comments: Remove All Comments`
