### ISSUE TITLE
Support Zig

### ISSUE THREAD

**Issue by Nabav** [rioj7/remove-comments#11]
Zig comments: https://ziglang.org/documentation/master/#Comments

**Comment by rioj7** [comment]
@Nabav  if I set the comment delimiter to `//` it also removes doc-comments and top-level-comments is this OK

**Comment by Nabav** [comment]
I would say yes. At the end, they are all comments.

**Comment by rioj7** [comment]
@Nabav  try v1.7.0

To keep the doc comments define the setting:

```json
"remove-comments.keep": {
  "zig": {
    "documentation": {
      "regex": "^(/(?!/)|!)"
    }
  }
}
```
