### ISSUE TITLE
Remove up to N blank lines above/below removed comment(s)

### ISSUE THREAD

**Issue by mike-clark-8192** [rioj7/remove-comments#15]
Hi. Great extension. Thanks. It'd be nice if there were two new preferences:

"Remove up to N blank lines above removed comments:" [integer] 
"Remove up to N blank lines below removed comments:" [integer] 

Blank lines are lines that contain entirely whitespace, e.g. matches `^[\t ]*$` .

**Comment by rioj7** [comment]
@mike-clark-8192  try v1.9.0

Can you explain the use case?

**Comment by mike-clark-8192** [comment]
Thanks a lot!  I am going to try it out tomorrow.  My personal use-case is that LLMs often like to write code where almost all statements get a comment -- even trivial statements -- and every comment is separated from the last statement by one or more empty lines. When removing comments from such code, the code can read awkwardly. For example, if I ask for a string permutation algorithm, we might get:
```javascript
// Define the function to generate all permutations of a given string
function permute(str, l, r) {
    // Base case: if the left index equals the right index, we have a valid permutation
    if (l === r) {

        // Print the current permutation
        console.log(str);
    } else {

        // Loop through all positions from l to r
        for (let i = l; i <= r; i++) {

            // Swap the current element with the element at the l index
            str = swap(str, l, i);

            // Recursively permute the remaining substring (l+1 to r)
            permute(str, l + 1, r);

            // Backtrack by swapping the elements back to their original positions
            str = swap(str, l, i);
        }
    }
}

// Helper function to swap characters at positions i and j in a string
function swap(str, i, j) {
    
    // Convert the string into an array of characters
    let arr = str.split('');

    // Swap the characters at positions i and j
    [arr[i], arr[j]] = [arr[j], arr[i]];

    // Convert the array back into a string and return it
    return arr.join('');
}
```

Maybe the comments are nice for this particular code, but it's just an example. `:)`
Say we don't need the comments for whatever reason.
If we "just" remove comments from this, we get:

```javascript
function permute(str, l, r) {
    if (l === r) {

        console.log(str);
    } else {

        for (let i = l; i <= r; i++) {

            str = swap(str, l, i);

            permute(str, l + 1, r);

            str = swap(str, l, i);
        }
    }
}

function swap(str, i, j) {

    let arr = str.split('');

    [arr[i], arr[j]] = [arr[j], arr[i]];

    return arr.join('');
}
```

And I think this result reads more nicely (which is output from your extension with the empty line removal features turned on):

```javascript
function permute(str, l, r) {
    if (l === r) {
        console.log(str);
    } else {
        for (let i = l; i <= r; i++) {
            str = swap(str, l, i);
            permute(str, l + 1, r);
            str = swap(str, l, i);
        }
    }
}
function swap(str, i, j) {
    let arr = str.split('');
    [arr[i], arr[j]] = [arr[j], arr[i]];
    return arr.join('');
}
```

Of course, you can guide an LLM with instructions to convince it to provide your preferred style in the first place -- but it is not always an LLM that writes code in such a way -- it might be a person that you are not in contact with. Or you might have obtained the code second-hand. Thus, I think it may be generally useful, especially when cleaning up a large amount of code in such a way.

**Comment by rioj7** [comment]
@mike-clark-8192  thanks for the use case.

Nice to know it works.

If you use sensible names most comments are not needed.

The code generated by the LLM is very inefficient.
You need to do the `split` and `join` only once and use a `_permute` that operates on `list`s and don't put print statements in the calculation function, make `permute` a generator function, return form the `if` so the `else` is not needed.
Now you have the permutations on your screen, not very useful for further processing.
