### ISSUE TITLE
Are there any plans to support vue single files?

### ISSUE THREAD

**Issue by Daotin** [rioj7/remove-comments#16]

**Comment by rioj7** [comment]
@Daotin

Can you give a hint what you expect and how these files look like.

A link to a doc page about Vue Single files.

What is the VSC Language Id of these files.

Which VSC extension does the syntax highlighting.

**Comment by rioj7** [comment]
@Daotin 

I did a little search and found [Single-File Components](https://vuejs.org/guide/scaling-up/sfc.html)

Does that mean you want different String/Comment detection in each section `<script>`, `<template>` and `<style>`?

**Comment by Daotin** [comment]
@rioj7 Thank you for your reply. 

Indeed, I would like to remove comments from `template`, `script`, and `style `sections simultaneously. 

However, since different language syntaxes can be used in each section (for example, Pug and regular HTML have different block comment styles), I'm unsure if my requirement is feasible.

Nevertheless, I found this VSCode extension [`Remove Vue Comment`](https://marketplace.visualstudio.com/items?itemName=RemoveVueComment.remove-vue-comments), which can remove comments from template, script, and style sections in `.vue` files at once. 

However, it seems that it doesn't provide proper support for templates using Pug language.

Here's an example demonstrating the extension's functionality:

```html
<template lang="pug">
  p {{ msg }}
  //- comment
  // comment

  //-
    comment
  //
    comment
</template>
<script setup>
// comment

const msg = 'Hello Vue 3 + Vite';

/**
 * comment
 */
const a = 1;
</script>
<style lang="scss">
$primary-color: #333;
body {
  /**
   * comment
   */
  color: $primary-color; // comment
}
</style>

```

After conversion:
```
<template lang="pug">
  p {{ msg }}
    comment
    comment
</template>
<script setup>
const msg = 'Hello Vue 3 + Vite';
const a = 1;
</script>
<style lang="scss">
$primary-color: #333;
body {
  color: $primary-color;
}
</style>

```

**Comment by rioj7** [comment]
@Daotin That `Remove Vue Comment` extension has the same problem as the extension [Remove Comments](https://marketplace.visualstudio.com/items?itemName=plibither8.remove-comments) by plibither8.

Comment like text in strings are also removed

```js
let my_url = 'http://www.example.com';
```

And the extension does not parse the file and apply different rules to different sections based on the `lang` attribute

**Comment by Daotin** [comment]
@rioj7 Thank you very much. The Pug language has taken effect on the template tag of the vue file! We look forward to the support of the full version.👍

**Comment by rioj7** [comment]
@Daotin  try v1.11.0

**Comment by Daotin** [comment]
> @Daotin try v1.11.0
> 
> Maybe using the settings `remove-comments.removeBlankLines.before` and `remove-comments.removeBlankLines.after` will make it even cleaner

@rioj7 It seems that the `block comments` in the script have not been deleted?

The source file:

```js
<template lang="pug">
  p {{ msg }}
  //- comment
  // comment






  //-
    comment
  //
    comment
</template>
<script setup>
// comment

const msg = 'Hello Vue 3 + Vite';

/**
 * comment
 */
const a = 1;
</script>
<style lang="scss">
$primary-color: #333;
body {
  /**
   * comment
   */
  color: $primary-color; // comment
}
</style>

```

after converted:

```js
<template lang="pug">
  p {{ msg }}



</template>
<script setup>
const msg = 'Hello Vue 3 + Vite';

/**
 * comment
 */
const a = 1;
</script>
<style lang="scss">
$primary-color: #333;
body {
  color: $primary-color;
}
</style>

```

**Comment by rioj7** [comment]
@Daotin  In Javascript a `/** */` comment is a Doc String, it specifies types of variables and input and result types of functions.

Use `/* */` comments

**Comment by Daotin** [comment]
@rioj7  I understand, but it's still a comment, can't I remove it? Sometimes do I want to remove comments like the following, or do I have to rewrite them into `/* */`?

```js
/*************************************
 * comment
 *************************************/
```

**Comment by rioj7** [comment]
@Daotin I'm not adding some code to analyze if it is a Doc String. You can use the command:

**Comments: Mark JSDOC String as comment. For next removal only.**

**Comment by rioj7** [comment]
@Daotin what I can do is add `/*** */` as comment separators

**Comment by Daotin** [comment]
> @Daotin I'm not adding some code to analyze if it is a Doc String. You can use the command:
> 
> **Comments: Mark JSDOC String as comment. For next removal only.**

@rioj7  This is very good. Thank you very much. Can you consider making it a configuration option? It is not checked by default. If checked, JSDOC will be used as a comment. Of course, maybe it’s just a naive idea haha.

**Comment by rioj7** [comment]
@Daotin  in v1.13.0 `/*** ... */` comments are always deleted in JavaScript
