### ISSUE TITLE
JSON file problem

### ISSUE THREAD

**Issue by Chrosea** [rioj7/remove-comments#4]
Can't remove JSON file comments in the format of `/* ... */`

For example in tsconfig.json for typescript like below, comments will not be removed
```JSON
{
  "compilerOptions": {
    "allowJs": true, /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get errors from these files. */
  }
}
```

**Comment by rioj7** [comment]
@Chrosea  Where is the documentation of the types of comment allowed in JSON? I can't find a mention on the Typescript website. There are some issues where they mention comments but they ask for PR's.

VSC allows `//` in tasks and launch JSON files.

Looking at the Token/Scope of the `tsconfig.json` it classifies `/* */` as a comment. I will add that to the `jsonc` language
