### ISSUE TITLE
[Javascript] All regions removed

### ISSUE THREAD

**Issue by LatenPath** [rioj7/remove-comments#9]
```javascript
  // #region constructor
    constructor(name, age) {
      this.name = name;
      this.age = age;
    }
  // #endregion
```

In JavaScript, `#region` will mark as `"// #region"` and `"// #endregion"` => which make extension remove them as comment.

Can we have an option in extension to exclude some prefix like that when remove.

**Comment by LatenPath** [comment]
please note that we can have many whitespace between "//" and "#region".
This is valid #region too:
![image](https://github.com/rioj7/remove-comments/assets/145383056/d9fa0d5b-ab9c-4099-8721-12d1697e8011)

**Comment by rioj7** [comment]
@LatenPath try v1.6.0

define the following setting:

```json
"remove-comments.keep": {
  "all": {
    "region": {
      "regex": "^\\s*#(end)?region"
    }
  }
}
```

or

```json
"remove-comments.keep": {
  "javascript": {
    "region": {
      "regex": "^\\s*#(end)?region"
    }
  }
}
```

**Comment by LatenPath** [comment]
Great idea! It not only save my region, but also my Note and other Todo things!
